spec:
  name: feather-press
  region: blr
  services:
    - name: web
      environment_slug: node-js
      github:
        repo: hash066/feather-press
        branch: main
        deploy_on_push: true
      build_command: npm ci && npm run build
      run_command: npm start
      http_port: 3001
      instance_count: 1
      instance_size_slug: basic-xxs
      routes:
        - path: /
      health_check:
        http_path: /api/health
      envs:
        # Database
        - key: MYSQL_HOST
          scope: RUN_AND_BUILD_TIME
          value: ""
        - key: MYSQL_PORT
          scope: RUN_AND_BUILD_TIME
          value: "3306"
        - key: MYSQL_USER
          scope: RUN_AND_BUILD_TIME
          value: ""
        - key: MYSQL_PASSWORD
          scope: RUN_AND_BUILD_TIME
          value: ""
        - key: MYSQL_DATABASE
          scope: RUN_AND_BUILD_TIME
          value: feather_press
        # Storage provider
        - key: STORAGE_PROVIDER
          scope: RUN_AND_BUILD_TIME
          value: spaces
        - key: SPACES_ENDPOINT
          scope: RUN_AND_BUILD_TIME
          value: "https://nyc3.digitaloceanspaces.com"
        - key: SPACES_REGION
          scope: RUN_AND_BUILD_TIME
          value: nyc3
        - key: SPACES_BUCKET
          scope: RUN_AND_BUILD_TIME
          value: ""
        - key: SPACES_KEY
          scope: RUN_AND_BUILD_TIME
          value: ""
        - key: SPACES_SECRET
          scope: RUN_AND_BUILD_TIME
          value: ""
        - key: PUBLIC_CDN_BASE
          scope: RUN_AND_BUILD_TIME
          value: ""
        - key: NODE_ENV
          scope: RUN_AND_BUILD_TIME
          value: production
